In [209]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import cm
from sklearn.decomposition import PCA
from sklearn.manifold import Isomap
from sklearn.preprocessing import MinMaxScaler
from model.feature_selection import feature_selection
from model.calculate_features import CalculateFeatures
from model.feature_selection import feature_selection
%matplotlib qt


In [2]:
dtypes = {'Magnitude': np.float64, 'Latitude': np.float64, 'Longitude': np.float64, 'Depth': np.float64}
df = pd.read_csv('../../data/DATA_3_south.csv', delimiter=',', dtype=dtypes, parse_dates=["Datetime"],
                 date_parser=np.datetime64)
df = df.reset_index(drop=True)
df.head()

Magnitude  Latitude  Longitude  Depth            Datetime
0        3.9   16.8023   -94.9130  114.9 2017-01-01 00:54:31
1        3.9   15.2842   -93.1210  100.7 2017-01-01 04:10:39
2        3.9   17.4503   -94.9543  138.3 2017-01-01 04:23:51
3        3.9   16.4077   -93.7075  139.4 2017-01-01 04:26:01
4        4.1   16.7017   -98.8633   27.5 2017-01-01 08:49:23

In [3]:
df_model = CalculateFeatures(df, 50, trimFeatures=False)

In [4]:
features = df_model.features
features_trimmed = df_model.get_trim_features()
features_trimmed.sort_values('next14dMaxMag', inplace=True)

In [9]:
main_features =  features[['meanMag', 'maxAMag', 'maxEMag', 'magDef', 'a', 'b', 'bStd', 'grcStd', 'elapsedT', 'rateSqrtEnergy', 'meanT',
     'meanTStd', 'pMag6', 'zSeismicRateChange', 'bSeismicRateChange', 'last7dMaxMag','next14dMaxMag']]
f_X = main_features.iloc[:-2]
f_Y = main_features.iloc[-1]
X = f_X.to_numpy()
Y = f_Y.to_numpy()

In [11]:
X

array([[  3.92      ,   4.4       ,   4.45216564, ...,          nan,
          4.4       ,   5.        ],
       [  3.918     ,   4.4       ,   4.44276117, ...,  59.39435197,
          4.4       ,   5.        ],
       [  3.918     ,   4.4       ,   4.44276117, ..., 138.45064659,
          4.4       ,   5.        ],
       ...,
       [  3.91      ,   4.3       ,   4.43120285, ..., -47.53466427,
          4.6       ,   4.3       ],
       [  3.91      ,   4.3       ,   4.43120285, ...,  12.20099714,
          4.6       ,   4.3       ],
       [  3.918     ,   4.3       ,   4.46340772, ...,  76.10938487,
          4.6       ,   4.3       ]])

In [43]:
Y_Scaler = MinMaxScaler()
X_Scaler = MinMaxScaler()
f_Y_norm = Y_Scaler.fit_transform(Y)
f_X_norm = X_Scaler.fit_transform(X)

In [ ]:
f_X_norm32 = f_X_norm.astype(np.float32)
f_Y_norm32 = f_Y_norm.astype(np.float32)

In [83]:
from pprint import pprint

for i in range(len(X.T)):
    pprint(list(zip(f_X_norm.T[i],X.T[i],f_X_norm32.T[i])))

TypeError: pprint() takes from 1 to 5 positional arguments but 39171 were given

In [ ]:
# evaluate isomap with logistic regression algorithm for classification
pca = PCA(n_components=2)
pca.fit(f_X_norm32.T, f_Y_norm32.T)
pca_components = pca.components_

In [33]:
cmap = cm.get_cmap("viridis")
colors = list(map(cmap, f_Y_norm32.T[0]))
sizes = np.power(10, f_Y_norm32.T[0] + .25)

In [ ]:
%matplotlib qt
plt.scatter(pca_components[0], pca_components[1], s=sizes, color=colors)

In [6]:
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

corrMatrix = features.corr()
sn.heatmap(corrMatrix, annot=True)
plt.show()


dtype('bool')

In [ ]:
embedding = Isomap(n_components=2)
X_transformed = embedding.fit_transform(f_X_norm32, a)

%matplotlib qt
fix, ax = plt.subplots()
ax.set_facecolor((0, 0, .420, 0.125))
ax.scatter(X_transformed.T[0], X_transformed.T[1], s=sizes, color=colors)

In [12]:
import matplotlib.pyplot as plt
% matplotlib qt
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(X_transformed.T[0], X_transformed.T[1], X_transformed.T[2], s=sizes, color=colors);

[(3.892, 3.8920000000000003, 0.11578941),
 (4.4, 4.4, 0.09523809),
 (4.3330493, 4.333049433249058, 0.11037946),
 (0.06695057, 0.06695056675094246, 0.18876411),
 (13.772086, 13.772085897522178, 0.6113184),
 (3.178382, 3.178381901633518, 0.6122097),
 (14.84226, 14.842260458553298, 0.1901691),
 (72.10736, 72.10735804046563, 0.4648822),
 (221307.0, 221307.0, 0.32300612),
 (153659.0, 153658.99434200482, 0.0013076877),
 (4516.469, 4516.469387755102, 0.32300612),
 (1588523300.0, 1588523242.2315843, 0.7638664),
 (8.5056714e-20, 8.50567119662474e-20, 3.0724385e-14),
 (299.4161, 299.41609843159733, 0.15041952),
 (26.791641, 26.79164123974763, 0.47528192),
 (4.6, 4.6, 0.100000024)]

In [36]:

f_X_norm

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

array([0.61052632, 0.21428571, 0.64587154, 0.11780502, 0.10093372,
       0.10051837, 0.04124154, 0.06388119, 0.37693954, 0.00190763,
       0.37693954, 0.14489289, 0.00604487, 0.06915661, 0.45411116,
       0.25      ])

In [101]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

corrMatrix = main_features.corr()
sns.heatmap(corrMatrix, annot=True,cmap="bwr")
plt.show()

In [22]:

features

old_index              firstT               lastT  meanMag  maxAMag  \
0             49 2017-01-01 00:54:31 2017-01-05 19:01:25    3.920      4.4   
1             50 2017-01-01 04:10:39 2017-01-05 23:48:11    3.918      4.4   
2             51 2017-01-01 04:23:51 2017-01-06 03:34:05    3.918      4.4   
3             52 2017-01-01 04:26:01 2017-01-06 07:44:08    3.918      4.4   
4             53 2017-01-01 08:49:23 2017-01-06 08:43:52    3.916      4.4   
...          ...                 ...                 ...      ...      ...   
39406      39455 2021-05-27 05:46:09 2021-05-29 13:59:14    3.910      4.3   
39407      39456 2021-05-27 05:48:53 2021-05-29 14:15:02    3.910      4.3   
39408      39457 2021-05-27 06:21:49 2021-05-29 16:09:39    3.918      4.3   
39409      39458 2021-05-27 06:49:52 2021-05-29 19:54:14    3.918      4.3   
39410      39459 2021-05-27 06:51:27 2021-05-30 01:38:49    3.926      4.3   

        maxEMag    magDef          a         b      bStd     grcStd  elapsedT  \
0      4.452166 -0.052166  11.613363  2.608475  9.326278  46.432020    410814   
1      4.442761 -0.042761  11.745555  2.643751  9.626963  47.781183    416252   
2      4.442761 -0.042761  11.745555  2.643751  9.626963  47.781183    429014   
3      4.442761 -0.042761  11.745555  2.643751  9.626963  47.781183    443887   
4      4.433093 -0.033093  11.886313  2.681268  9.950613  49.237072    431669   
...         ...       ...        ...       ...       ...        ...       ...   
39406  4.431203 -0.131203  12.062507  2.722174  9.126619  52.860716    202385   
39407  4.431203 -0.131203  12.062507  2.722174  9.126619  52.860716    203169   
39408  4.463408 -0.163408  11.566727  2.591457  8.084512  47.124461    208070   
39409  4.463408 -0.163408  11.566727  2.591457  8.084512  47.124461    219862   
39410  4.494713 -0.194713  11.112065  2.472252  7.194328  41.687844    240442   

       rateSqrtEnergy        meanT      meanTStd         pMag6  \
0        87680.297260  8383.959184  1.483392e+09  2.234340e-16   
1        86280.164530  8494.938776  1.483401e+09  1.372440e-16   
2        83713.564233  8755.387755  1.483409e+09  1.372440e-16   
3        80908.634508  9058.918367  1.483418e+09  1.372440e-16   
4        82953.115590  8809.571429  1.483427e+09  8.173144e-17   
...               ...          ...           ...           ...   
39406   171097.340298  4130.306122  1.622188e+09  4.644661e-17   
39407   170437.100228  4146.306122  1.622192e+09  4.644661e-17   
39408   169112.377303  4246.326531  1.622197e+09  2.826576e-16   
39409   160042.264445  4486.979592  1.622201e+09  2.826576e-16   
39410   149110.346196  4906.979592  1.622205e+09  1.467188e-15   

       zSeismicRateChange  bSeismicRateChange  last7dMaxMag  next14dMaxMag  
0                     NaN                 NaN           4.4            5.0  
1              521.440313           59.394352           4.4            5.0  
2              798.811617          138.450647           4.4            5.0  
3              862.351436          158.927921           4.4            5.0  
4              781.600921         -128.429872           4.4            5.0  
...                   ...                 ...           ...            ...  
39406          392.237173          -47.534664           4.6            4.3  
39407          197.989899           12.200997           4.6            4.3  
39408          495.025252           76.109385           4.6            4.3  
39409          767.854153          180.894967           4.6            4.3  
39410         1014.396372          307.013179           4.3            NaN  

[39411 rows x 20 columns]

In [102]:
# creating set to hold the correlated features
model.

In [103]:
corr_features

{'b', 'maxEMag', 'meanT'}

'next14dMaxMag'

<AxesSubplot:>

array([[ 1.        ,  0.62784803,  0.95624834,  0.29845348, -0.8932318 ,
        -0.89318061, -0.13523588, -0.58589166, -0.18319824,  0.4351462 ,
        -0.18319824, -0.23925359,  0.29997525,         nan,         nan,
         0.5314931 ,  0.33436521],
       [ 0.62784803,  1.        ,  0.41285029,  0.92837404, -0.38578341,
        -0.38494519,  0.58021633, -0.01716123, -0.09159707,  0.39871869,
        -0.09159707, -0.09671284,  0.09703312,         nan,         nan,
         0.43303105,  0.18498849],
       [ 0.95624834,  0.41285029,  1.        ,  0.04478364, -0.94134758,
        -0.94153961, -0.37858357, -0.73994447, -0.18190486,  0.37846012,
        -0.18190486, -0.23101663,  0.31184035,         nan,         nan,
         0.47689734,  0.32856344],
       [ 0.29845348,  0.92837404,  0.04478364,  1.        , -0.03902856,
        -0.03803082,  0.7908812 ,  0.2831078 , -0.02624152,  0.28290001,
        -0.02624152, -0.01181284, -0.0208156 ,         nan,         nan,
         0.28036819

In [119]:
f_X.dropna(inplace=True)
f_X.corr()

C:\Users\fof\AppData\Local\Temp/ipykernel_2364/1493744337.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_X.dropna(inplace=True)


meanMag   maxAMag   maxEMag    magDef         a  \
meanMag             1.000000  0.627844  0.956248  0.298449 -0.893231   
maxAMag             0.627844  1.000000  0.412844  0.928374 -0.385777   
maxEMag             0.956248  0.412844  1.000000  0.044777 -0.941347   
magDef              0.298449  0.928374  0.044777  1.000000 -0.039022   
a                  -0.893231 -0.385777 -0.941347 -0.039022  1.000000   
b                  -0.893180 -0.384939 -0.941539 -0.038024  0.999988   
bStd               -0.135243  0.580215 -0.378592  0.790880  0.408230   
grcStd             -0.585893 -0.017159 -0.739947  0.283110  0.807677   
elapsedT           -0.183171 -0.091562 -0.181876 -0.026215  0.105185   
rateSqrtEnergy      0.435143  0.398715  0.378456  0.282897 -0.276040   
meanT              -0.183171 -0.091562 -0.181876 -0.026215  0.105185   
meanTStd           -0.239293 -0.096746 -0.231057 -0.011832  0.210620   
pMag6               0.299976  0.097033  0.311841 -0.020816 -0.158276   
zSeismicRateChange -0.106710 -0.039036 -0.110740  0.002370  0.070939   
bSeismicRateChange -0.024255 -0.047275 -0.014060 -0.046116  0.011426   
last7dMaxMag        0.531486  0.433022  0.476889  0.280361 -0.376826   
next14dMaxMag       0.334359  0.184981  0.328557  0.068828 -0.248045   

                           b      bStd    grcStd  elapsedT  rateSqrtEnergy  \
meanMag            -0.893180 -0.135243 -0.585893 -0.183171        0.435143   
maxAMag            -0.384939  0.580215 -0.017159 -0.091562        0.398715   
maxEMag            -0.941539 -0.378592 -0.739947 -0.181876        0.378456   
magDef             -0.038024  0.790880  0.283110 -0.026215        0.282897   
a                   0.999988  0.408230  0.807677  0.105185       -0.276040   
b                   1.000000  0.409402  0.808575  0.105637       -0.276219   
bStd                0.409402  1.000000  0.732119  0.025655        0.019868   
grcStd              0.808575  0.732119  1.000000  0.072800       -0.165164   
elapsedT            0.105637  0.025655  0.072800  1.000000       -0.383175   
rateSqrtEnergy     -0.276219  0.019868 -0.165164 -0.383175        1.000000   
meanT               0.105637  0.025655  0.072800  1.000000       -0.383175   
meanTStd            0.210698  0.064600  0.133677  0.166976       -0.222172   
pMag6              -0.158514 -0.064651 -0.108465 -0.090286        0.186121   
zSeismicRateChange  0.071176  0.024796  0.049401  0.410839       -0.181815   
bSeismicRateChange  0.011446 -0.019236  0.006019  0.032942       -0.050210   
last7dMaxMag       -0.376884  0.045362 -0.227346 -0.469173        0.527722   
next14dMaxMag      -0.248224 -0.050951 -0.170477 -0.269971        0.350011   

                       meanT  meanTStd     pMag6  zSeismicRateChange  \
meanMag            -0.183171 -0.239293  0.299976           -0.106710   
maxAMag            -0.091562 -0.096746  0.097033           -0.039036   
maxEMag            -0.181876 -0.231057  0.311841           -0.110740   
magDef             -0.026215 -0.011832 -0.020816            0.002370   
a                   0.105185  0.210620 -0.158276            0.070939   
b                   0.105637  0.210698 -0.158514            0.071176   
bStd                0.025655  0.064600 -0.064651            0.024796   
grcStd              0.072800  0.133677 -0.108465            0.049401   
elapsedT            1.000000  0.166976 -0.090286            0.410839   
rateSqrtEnergy     -0.383175 -0.222172  0.186121           -0.181815   
meanT               1.000000  0.166976 -0.090286            0.410839   
meanTStd            0.166976  1.000000 -0.060937            0.130929   
pMag6              -0.090286 -0.060937  1.000000           -0.057062   
zSeismicRateChange  0.410839  0.130929 -0.057062            1.000000   
bSeismicRateChange  0.032942  0.002068 -0.000975            0.010018   
last7dMaxMag       -0.469173 -0.247479  0.185705           -0.250305   
next14dMaxMag      -0.269971 -0.241378  0.143616           -0.160365   

                    bS

In [120]:
sns.heatmap(pd.DataFrame(np.corrcoef(f_X.to_numpy().T)))

<AxesSubplot:>

In [212]:
df = f_X

feature_selection(df,.95)

(['maxEMag', 'meanT', 'b'],
 ['meanTStd',
  'bSeismicRateChange',
  'bStd',
  'last7dMaxMag',
  'elapsedT',
  'magDef',
  'grcStd',
  'a',
  'rateSqrtEnergy',
  'pMag6',
  'next14dMaxMag',
  'meanMag',
  'zSeismicRateChange',
  'maxAMag'])

AttributeError: module 'model' has no attribute 'feature_selection'